version: '3.8'

services:
  stable:
    build: .
    container_name: stable_app
    environment:
      - ENVIRONMENT=stable
      - GREETING=Stable Version - Hello, World!
    expose:
      - "4000"

  canary:
    build: .
    container_name: canary_app
    environment:
      - ENVIRONMENT=canary
      - GREETING=Canary Version - New Features!
    expose:
      - "4000"

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stable
      - canary

