apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
    version: blue  # Initially route all traffic to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP

